MAIN_MENU_TITLE = ""

MAIN_TODAY_TASKS = "MAIN_TODAY_TASKS"
MAIN_WEEK_TASKS = "MAIN_WEEK_TASKS"
MAIN_ALL_TASKS = "MAIN_ALL_TASKS"
MAIN_MISSED_TASKS = "MAIN_MISSED_TASKS"
MAIN_ADD_TASK = "MAIN_ADD_TASK"
MAIN_DELETE_TASK = "MAIN_DELETE_TASK"
MAIN_EXIT = "MAIN_EXIT"

MAIN_OPTIONS = {
    MAIN_TODAY_TASKS: ("1", "Today's tasks"),
    MAIN_WEEK_TASKS: ("2", "Week's tasks"),
    MAIN_ALL_TASKS: ("3", "All tasks"),
    MAIN_MISSED_TASKS: ("4", "Missed tasks"),
    MAIN_ADD_TASK: ("5", "Add a task"),
    MAIN_DELETE_TASK: ("6", "Delete a task"),
    MAIN_EXIT: ("0", "Exit"),
}

MAIN_MENU = (MAIN_MENU_TITLE, MAIN_OPTIONS)
